export default {
    top: "150",
    left: "440",
    width: "300",
    height: "200",
    noPlace: true,
    visible: true,
    disable: false,
    zIndex: 0,

    type: "border-card",
    tagPosition: "top",
    gutter: 10,
    justify: "start",
    childComponents: [
        {
            componentName: "elContainer",
            name: "ContentArea",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            // background: "#fff",
            position: "relative",
            noPlace: false,
            noDrag: true,
            visible: true,
            disable: false,
            pid: 0,
            zIndex: 0,
            span: 8,
            childComponents: []
        },
        {
            componentName: "elContainer",
            name: "ContentArea",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            // background: "#fff",
            position: "relative",
            noPlace: false,
            noDrag: true,
            visible: true,
            disable: false,
            pid: 0,
            zIndex: 0,
            span: 8,
            childComponents: []
        },
        {
            componentName: "elContainer",
            name: "ContentArea",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            // background: "#fff",
            position: "relative",
            noPlace: false,
            noDrag: true,
            visible: true,
            disable: false,
            pid: 0,
            zIndex: 0,
            span: 8,
            childComponents: []
        }
    ]
}
