export default {
    top: "0",
    left: "0",
    width: "120",
    height: "40",
    noPlace: true,
    visible: true,
    disable: false,
    zIndex: 0,
    size: "custom",
    内容: "",
    type: "text",
    placeholder: "请输入..",
    maxlength:-1,
}
