export default {
    top: "inherit",
    left: "inherit",
    width: "146",
    height: "32",
    right: "0",
    bottom: "inherit",
    禁止放置: true,
    visible: true,
    disable: false,
    zIndex: 0,
    block: true,
    ghost: false,
    loading: false,
    shape: "rectangle",
    size: "medium",
    theme: "primary",
    variant: "base",
    text:"按钮",
}
