export default {
    top: "150",
    left: "440",
    width: "300",
    height: "200",
    现行选中项: "0",
    禁止放置: true,
    可视: true,
    禁止: false,
    层级: 0,
    自定义渲染:true,

    风格类型: "border-card",
    标签位置: "top",
    列间隔: 10,
    对齐方式: "start",
    布局方式: "header-main",
    子组件: [
        {
            组件名称: "elContainer",
            名称: "content area header",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            // background: "#fff",
            position: "relative",
            禁止放置: false,
            禁止拖动: true,
            可视: true,
            禁止: false,
            父容器id: 0,
            层级: 0,
            子组件: []
        },

        {
            组件名称: "elContainer",
            名称: "content area main",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            // background: "red",
            position: "relative",
            禁止放置: false,
            禁止拖动: true,
            可视: true,
            禁止: false,
            层级: 0,
            子容器: true,
            父容器id: 0,
            子组件: []
        },

        {
            组件名称: "elContainer",
            名称: "content area footer",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            // background: "green",
            position: "relative",
            禁止放置: false,
            禁止拖动: true,
            可视: true,
            禁止: false,
            层级: 0,
            子容器: true,
            父容器id: 0,
            子组件: []
        },

        {
            组件名称: "elContainer",
            名称: "content area aside",
            top: "0",
            left: "0",
            width: "100px",
            height: "100%",
            // background: "green",
            position: "relative",
            禁止放置: false,
            禁止拖动: true,
            可视: true,
            禁止: false,
            层级: 0,
            子容器: true,
            父容器id: 0,
            子组件: []
        },

    ]
}
