export default {
    top: "0",
    left: "0",
    width: "80",
    height: "32",
    not_place: true,
    visible: true,
    disable: false,
    zIndex: 0,
    block: true,
    ghost: false,
    loading: false,
    shape: "rectangle",
    size: "medium",
    theme: "primary",
    variant: "base",
    text:"按钮",
}
