export default {
    top: "150",
    left: "440",
    width: "300",
    height: "300",
    现行选中项: "0",
    禁止放置: true,
    可视: true,
    禁止: false,
    层级: 0,
    y轴滚动模式选项: "hidden",
    x轴滚动模式选项: "hidden",
    风格类型: "border-card",
    标签位置: "top",
    自定义渲染:true,
    子组件: [
        {
            组件名称: "elContainer",
            名称: "content area",
            标题: "tab",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            禁止放置: false,
            禁止拖动: true,
            可视: true,
            禁止: false,
            父容器id: 0,
            层级: 0,
            子组件: []
        },
        {
            组件名称: "elContainer",
            名称: "content area",
            标题: "tab",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            禁止放置: false,
            禁止拖动: true,
            可视: true,
            禁止: false,
            父容器id: 0,
            层级: 0,
            子组件: []
        },
    ]
}
