export default {
    top: "150",
    left: "440",
    width: "300",
    height: "300",
    现行选中项: "0",
    noPlace: true,
    可视: true,
    禁止: false,
    层级: 0,
    y轴滚动模式选项: "hidden",
    x轴滚动模式选项: "hidden",
    风格类型: "border-card",
    标签位置: "top",

    子组件: [
        {
            组件名称: "elContainer",
            名称: "ContentArea",
            标题: "tab",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            noPlace: false,
            禁止拖动: true,
            可视: true,
            禁止: false,
            父容器id: 0,
            层级: 0,
            子组件: []
        },
        {
            组件名称: "elContainer",
            名称: "ContentArea",
            标题: "tab",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            noPlace: false,
            禁止拖动: true,
            可视: true,
            禁止: false,
            父容器id: 0,
            层级: 0,
            子组件: []
        },
    ]
}
