// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function E保存(arg1:string,arg2:string):Promise<string>;

export function E保存件对话框():Promise<string>;

export function E创建函数(arg1:string,arg2:string,arg3:string):Promise<string>;

export function E打开文件对话框():Promise<string>;

export function E读入文件(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;
