// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function E下载github项目(arg1:string,arg2:string):Promise<string>;

export function E保存(arg1:string,arg2:string):Promise<string>;

export function E保存件对话框():Promise<string>;

export function E停止命令():Promise<string>;

export function E创建函数(arg1:string,arg2:string,arg3:string):Promise<string>;

export function E发送跳转代码到ide(arg1:string,arg2:string,arg3:number):Promise<boolean>;

export function E取当前目录():Promise<string>;

export function E取文件修改时间(arg1:string):Promise<string>;

export function E取运行目录():Promise<string>;

export function E取配置信息():Promise<string>;

export function E打开文件对话框():Promise<string>;

export function E打开选择文件夹对话框():Promise<string>;

export function E搜索文件(arg1:string,arg2:string):Promise<Array<string>>;

export function E文件是否存在(arg1:string):Promise<boolean>;

export function E文件枚举(arg1:string):Promise<Array<string>>;

export function E检查更新():Promise<string>;

export function E添加文件监视(arg1:string):Promise<string>;

export function E清空文件监视():Promise<string>;

export function E读入文件(arg1:string):Promise<string>;

export function E运行命令(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;
