// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function E保存(arg1, arg2) {
  return window['go']['main']['App']['E保存'](arg1, arg2);
}

export function E保存件对话框() {
  return window['go']['main']['App']['E保存件对话框']();
}

export function E停止命令() {
  return window['go']['main']['App']['E停止命令']();
}

export function E创建函数(arg1, arg2, arg3) {
  return window['go']['main']['App']['E创建函数'](arg1, arg2, arg3);
}

export function E发送跳转代码到ide(arg1, arg2, arg3) {
  return window['go']['main']['App']['E发送跳转代码到ide'](arg1, arg2, arg3);
}

export function E取配置信息(arg1) {
  return window['go']['main']['App']['E取配置信息'](arg1);
}

export function E打开文件对话框() {
  return window['go']['main']['App']['E打开文件对话框']();
}

export function E文件枚举(arg1) {
  return window['go']['main']['App']['E文件枚举'](arg1);
}

export function E检查更新() {
  return window['go']['main']['App']['E检查更新']();
}

export function E读入文件(arg1) {
  return window['go']['main']['App']['E读入文件'](arg1);
}

export function E运行命令(arg1, arg2) {
  return window['go']['main']['App']['E运行命令'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
