package mainxx

import (
	"encoding/json"
	"fmt"
	"strings"
)

func mainxxxx() {
	text := `
[
  {"type":"directory","name":".","contents":[
    {"type":"directory","name":"./单选框","contents":[
      {"type":"file","name":"./单选框/单选框.js"},
      {"type":"file","name":"./单选框/单选框.vue"},
      {"type":"file","name":"./单选框/单选框属性.vue"}
    ]},
    {"type":"directory","name":"./多选框","contents":[
      {"type":"file","name":"./多选框/多选框.js"},
      {"type":"file","name":"./多选框/多选框.vue"},
      {"type":"file","name":"./多选框/多选框属性.vue"}
    ]},
    {"type":"directory","name":"./布局容器","contents":[
      {"type":"file","name":"./布局容器/布局容器.js"},
      {"type":"file","name":"./布局容器/布局容器属性.vue"}
    ]},
    {"type":"directory","name":"./常用布局","contents":[
      {"type":"file","name":"./常用布局/常用布局.js"},
      {"type":"file","name":"./常用布局/常用布局.vue"},
      {"type":"file","name":"./常用布局/常用布局属性.vue"}
    ]},
    {"type":"directory","name":"./开关","contents":[
      {"type":"file","name":"./开关/开关.js"},
      {"type":"file","name":"./开关/开关.vue"},
      {"type":"file","name":"./开关/开关属性.vue"}
    ]},
    {"type":"directory","name":"./弹性布局","contents":[
      {"type":"file","name":"./弹性布局/弹性布局.js"},
      {"type":"file","name":"./弹性布局/弹性布局.vue"},
      {"type":"file","name":"./弹性布局/弹性布局属性.vue"}
    ]},
    {"type":"directory","name":"./按钮","contents":[
      {"type":"file","name":"./按钮/按钮.js"},
      {"type":"file","name":"./按钮/按钮.vue"},
      {"type":"file","name":"./按钮/按钮属性.vue"}
    ]},
    {"type":"directory","name":"./提示框","contents":[
      {"type":"file","name":"./提示框/提示框.js"},
      {"type":"file","name":"./提示框/提示框.vue"},
      {"type":"file","name":"./提示框/提示框属性.vue"}
    ]},
    {"type":"directory","name":"./标签","contents":[
      {"type":"file","name":"./标签/标签.js"},
      {"type":"file","name":"./标签/标签.vue"},
      {"type":"file","name":"./标签/标签属性.vue"}
    ]},
    {"type":"directory","name":"./树形框","contents":[
      {"type":"file","name":"./树形框/树形框.js"},
      {"type":"file","name":"./树形框/树形框.vue"},
      {"type":"file","name":"./树形框/树形框属性.vue"}
    ]},
    {"type":"directory","name":"./编辑框","contents":[
      {"type":"file","name":"./编辑框/编辑框.js"},
      {"type":"file","name":"./编辑框/编辑框.vue"},
      {"type":"file","name":"./编辑框/编辑框属性.vue"}
    ]},
    {"type":"directory","name":"./自定义组件","contents":[
      {"type":"file","name":"./自定义组件/自定义组件.js"},
      {"type":"file","name":"./自定义组件/自定义组件.vue"},
      {"type":"file","name":"./自定义组件/自定义组件属性.vue"}
    ]},
    {"type":"directory","name":"./菜单","contents":[
      {"type":"file","name":"./菜单/菜单.js"},
      {"type":"file","name":"./菜单/菜单.vue"},
      {"type":"file","name":"./菜单/菜单属性.vue"}
    ]},
    {"type":"directory","name":"./表格","contents":[
      {"type":"file","name":"./表格/表格.js"},
      {"type":"file","name":"./表格/表格.vue"},
      {"type":"file","name":"./表格/表格属性.vue"}
    ]},
    {"type":"directory","name":"./进度条","contents":[
      {"type":"file","name":"./进度条/进度条.js"},
      {"type":"file","name":"./进度条/进度条.vue"},
      {"type":"file","name":"./进度条/进度条属性.vue"}
    ]},
    {"type":"directory","name":"./选择夹","contents":[
      {"type":"file","name":"./选择夹/选择夹.js"},
      {"type":"file","name":"./选择夹/选择夹.vue"},
      {"type":"file","name":"./选择夹/选择夹属性.vue"}
    ]},
    {"type":"directory","name":"./选择夹tw","contents":[
      {"type":"file","name":"./选择夹tw/选择夹tw.js"},
      {"type":"file","name":"./选择夹tw/选择夹tw.vue"},
      {"type":"file","name":"./选择夹tw/选择夹tw属性.vue"}
    ]}
  ]}
,
  {"type":"report","directories":18,"files":50}
]
`

	type AutoGenerated []struct {
		Type     string `json:"type"`
		Name     string `json:"name,omitempty"`
		Contents []struct {
			Type     string `json:"type"`
			Name     string `json:"name"`
			Contents []struct {
				Type string `json:"type"`
				Name string `json:"name"`
			} `json:"contents"`
		} `json:"contents,omitempty"`
		Directories int `json:"directories,omitempty"`
		Files       int `json:"files,omitempty"`
	}

	//解构
	var data AutoGenerated
	err := json.Unmarshal([]byte(text), &data)
	if err != nil {
		fmt.Println(err)
		return
	}
	test2 := `
		窗口 Window
		按钮 Button
		编辑框 TextEdit
		单选框 RadioButton
		多选框 CheckBox
		常用布局 CommonLayout
		开关 Switch
		弹性布局 FlexLayout
		提示框 Tooltip
		标签 Label
		树形框 Tree
		自定义组件 CustomComponent
		菜单 Menu
		表格 Table
		进度条 ProgressBar
		选择夹 Tabs
		选择夹tw TabsTW
		布局容器 Container
`
	// 分割处理 test2
	test2Arr := strings.Split(test2, "\n")
	kv := make(map[string]string)
	for _, v := range test2Arr {
		if v != "" {
			//删除全部换行
			v = strings.Replace(v, "\r", "", -1)
			//删除制表符
			v = strings.Replace(v, "\t", "", -1)
			//用空格分割加入kv
			vArr := strings.Split(v, " ")
			kv[vArr[0]] = vArr[1]

		}
	}
	fmt.Println(kv)
	p := `/Users/ll/Documents/GitHub/GoEasyDesigner/GoEasyDesigner/frontend/src/components/boxs/el/`

	//循环 data 读取路径
	for _, v := range data {
		for _, v2 := range v.Contents {
			//替换 ./ 为 ''
			//v3.Name = strings.Replace(v3.Name, "./", "", -1)
			v2.Name = strings.Replace(v2.Name, "./", "", -1)

			//读取对应的英文
			estr := kv[v2.Name]
			//fmt.Println(p+v3.Name, v2.Name, estr)
			// 新路径替换为英文
			newPath := strings.Replace(p+v2.Name, v2.Name, estr, -1)
			//newPath = strings.Replace(newPath, v2.Name+"属性.vue", estr+"属性.vue", -1)
			//newPath = strings.Replace(newPath, v2.Name+".js", estr+".js", -1)
			//newPath = strings.Replace(newPath, "属性.vue", "Attr.vue", -1)
			//fmt.Println(newPath, estr, v2.Name)
			//err := os.Rename(p+v2.Name, newPath)
			//if err != nil {
			//	fmt.Println(err)
			//}
		}
	}

}
