export default {
    top: "0",
    left: "0",
    width: "120",
    height: "40",
    noPlace: true,
    visible: true,
    disable: false,
    zIndex: 0,
    block: true,
    ghost: false,
    loading: false,
    shape: "rectangle",
    size: "medium",
    theme: "primary",
    variant: "base",
    text: "按钮",
}
