// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function E按钮1被点击() {
  return window['go']['main']['App']['E按钮1被点击']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
