export default {
    top: "150",
    left: "440",
    width: "300",
    height: "300",
    现行选中项: "0",
    禁止放置: true,
    可视: true,
    禁止: false,
    层级: 0,
    风格类型: "border-card",
    标签位置: "top",
    子组件: [
        {
            组件名称: "布局容器",
            名称: "内容区域1",
            标题: "选项卡1",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            禁止放置: false,
            禁止拖动: true,
            可视: true,
            禁止: false,
            父容器id: 0,
            层级: 0,
            子组件: []
        },
        {
            组件名称: "布局容器",
            名称: "内容区域1",
            标题: "选项卡2",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            禁止放置: false,
            禁止拖动: true,
            可视: true,
            禁止: false,
            父容器id: 0,
            层级: 0,
            子组件: []
        },
    ]
}
